version: "3.7"

services:
  config_deployment:
    build: python/deployment/installer/config-deployment
    image: ${REGISTRY_PREFIX}abstracto-db-deployment:${VERSION:-latest}
  template_deployment:
    build: python/deployment/installer/template-deployment
    image: ${REGISTRY_PREFIX}abstracto-template-deployment:${VERSION:-latest}
  rest_api_base:
    build:
      context: python/components/rest-api-base
      dockerfile: docker/Dockerfile
    image: ${REGISTRY_PREFIX}abstracto-rest-api:${VERSION:-latest}
  rest_api_image_gen:
    build:
      context: python/components/image-gen
      dockerfile: docker/Dockerfile
    image: ${REGISTRY_PREFIX}abstracto-rest-api-image-gen:${VERSION:-latest}
  core_api:
    build:
      context: python/components/core
      dockerfile: docker/Dockerfile
    image: ${REGISTRY_PREFIX}abstracto-rest-api-core:${VERSION:-latest}
  experience_api:
    build:
      context: python/components/experience-tracking
      dockerfile: docker/Dockerfile
    image: ${REGISTRY_PREFIX}abstracto-rest-api-experience:${VERSION:-latest}