---

- name: Prepare target directoy
  delegate_to: localhost
  file:
    path: "{{ installer_base_dir }}/liquibase/{{ artifact.group_id }}/{{ artifact.module }}"
    state: directory
    mode: '0755'

- name: "Download liquibase artifact {{ artifact.module }} in {{ artifact.group_id }}"
  delegate_to: localhost
  maven_artifact:
    group_id: "{{ artifact.group_id }}"
    artifact_id: "{{ artifact.module }}"
    dest: "{{ installer_base_dir }}/liquibase/{{ artifact.group_id }}-{{ artifact.module }}.zip"
    extension: zip
    version: "{{ artifact.version }}"
    repository_url: "file://{{ lookup('env','HOME') }}/.m2/repository"
    classifier: liquibase

- name: Extract artifact zip
  delegate_to: localhost
  unarchive:
    src: "{{ installer_base_dir }}/liquibase/{{ artifact.group_id }}-{{ artifact.module }}.zip"
    dest: "{{ installer_base_dir }}/liquibase/{{ artifact.group_id }}/{{ artifact.module }}"

- name: Render liquibase.properties template
  template:
    src: liquibase.properties.j2
    dest: "{{ installer_base_dir }}/liquibase/{{ artifact.group_id }}/{{ artifact.module }}/liquibase.properties"
  vars:
    - change_log_file: "{{ installer_base_dir }}//liquibase/{{ artifact.group_id }}/{{ artifact.module }}/{{ artifact.file }}"


- name: Run liquibase migration
  shell: "{{ liquibase_path }}/liquibase --defaultsFile={{ installer_base_dir }}/liquibase/{{ artifact.group_id }}/{{ artifact.module }}/liquibase.properties --logLevel=info update"

- name: Cleanup folder
  file:
    path: "{{ installer_base_dir }}/liquibase/{{ artifact.group_id }}"
    state: absent

- name: Cleanup zip
  file:
    path: "{{ installer_base_dir }}/liquibase/{{ artifact.group_id }}-{{ artifact.module }}.zip"
    state: absent