---

- name: Prepare target directoy
  delegate_to: localhost
  file:
    path: "{{ installer_base_dir }}/templates/{{ group_id }}/{{ module }}"
    state: directory
    mode: '0755'

- name: Download template artifact {{ module }} in {{ group_id }}
  delegate_to: localhost
  maven_artifact:
    group_id: "{{ group_id }}"
    artifact_id: "{{ module }}"
    dest: "{{ installer_base_dir }}/templates/{{ group_id }}-{{ module }}.zip"
    extension: zip
    version: "{{ version }}"
    repository_url: "file://{{ lookup('env','HOME') }}/.m2/repository"

- name: Extract artifact zip
  delegate_to: localhost
  unarchive:
    src: "{{ installer_base_dir }}/templates/{{ group_id }}-{{ module }}.zip"
    dest: "{{ installer_base_dir }}/templates/{{ group_id }}/{{ module }}"

- name: Deploy templates
  script: deploy_templates.py "{{ installer_base_dir }}/templates/{{ group_id }}/{{ module }}"
  args:
    executable: "{{ ansible_python_interpreter }}"

- name: Cleanup folder
  file:
    path: "{{ installer_base_dir }}/templates/"
    state: absent

