---

- name: Include custom variables
  include_vars:
    dir: "{{ installer_base_dir }}/ansible"
    depth: 1

- include_tasks: deploy_liquibase_change_log.yaml
  name: Deploying abstracto liquibase changelogs
  with_items: "{{ liquibase_artifacts }}"
  loop_control:
    loop_var: artifact
  when: execute_liquibase


- include_tasks: deploy_artifacts.yaml
  name: Deploying abstracto templates
  with_items: "{{ template_artifacts }}"
  loop_control:
    loop_var: artifact
  when: execute_templates


