=== Reminders

Provides the ability to schedule reminders.

Feature key: `remind`

==== Commands
Create a reminder::
* Usage: `remind <duration> <text>`
* Description: Creates a reminder with `text` which will be triggered after `duration`. This command uses duration parsing. The reminder will ping when the duration has passed and provide
the context of the reminder.
* Example: `remind 1h2m3s text` in order to be reminded in 1 hour 2 minutes and 3 seconds with the reason `text`
Cancelling a reminder::
* Usage `unRemind <reminderId>`
* Description: Cancels this reminder reminder and will cause this reminder to not be executed.
Listing all active reminders::
* Usage: `reminders`
* Description: Lists all the currently not yet executed reminders and information about each of them.


=== Starboard

Provides the ability to track note worthy posts in a separate channel, identified by the post target `starboard`, because the pins within a channel are limited to 50.
This feature works by users reacting to a message with the appropriate emote. By default this is `&#11088;`, but can be changed via the emote `star`.
There is a configurable threshold a message needs to reach in order to be posted to starboard.
The post in the starboard is continuously updated and depending on the current star count an associated emote is displayed.
When the poster of the message reacts to the message with a star, this is not counted. When the post is deleted from the starboard, the original message cannot appear on the starboard again.

Feature key: `starboard`

==== Emotes
* `star` to vote on posting something to starboard
* `star1` for level 1 of starboard
* `star2` for level 2 of starboard
* `star3` for level 3 of starboard
* `star4` for level 4 of starboard
* `starboardBadge1` used as marker for first place in the command `starStats`
* `starboardBadge2` used as marker for first place in the command `starStats`
* `starboardBadge3` used as marker for first place in the command `starStats`


==== Relevant system configuration
`starLvl1` The amount of stars necessary to appear on the starboard. Default: 5

`starLvl2` The amount of stars necessary in order for the level 2 emote to be used in the starboard post. Default: 8

`starLvl3` The amount of stars necessary in order for the level 3 emote to be used in the starboard post. Default: 13

`starLvl4` The amount of stars necessary in order for the level 4 emote to be used in the starboard post. Default: 17

==== Post targets
`starboard`:: The target used for the messages containing the starboard posts with the current star amount

==== Commands
Showing starboard statistics::
* Usage `starStats`
* Description: Shows the most starred posts, the member with the most received stars and the members rewarding the most stars.

=== Suggestions

This feature provides the ability for members to post suggestions containing text to the post target `suggestions`. These suggestions can then be accepted or denied by the moderators.

Feature key: `suggestion`

==== Post targets
`suggestions`:: the target of the messages containing the suggestions

==== Emotes
* `suggestionYes` for up-voting a suggestion
* `suggestionNo` for down-voting a suggestion

==== Commands
Creating a suggestion::
* Usage: `suggest <text>`
* Description: Posts the text to the `suggest` post target and places the emotes for up and down voting.
Accepting a suggestion::
* Usage: `accept <suggestionId> [note]`
* Description: Re-posts the suggestion identified by `suggestionId` and marks the suggestion as accepted. The optional `note` will be used in this re-post, if provided.
* Example: `accept 1 okay` in order to accept the suggestion `1` with the reason `okay`
Rejecting a suggestion::
* Usage: `reject <suggestionId> [note]`
* Description: Re-posts the suggestion identified by `suggestionId` and marks the suggestion as denied. The optional `note` will be used in this re-post, if provided.
* Example: `deny 1 not okay` in order to reject the suggestion `1` with the reason `not okay`

=== Miscellaneous

This feature provides some utility commands.

Feature key: `utility`

==== Commands
Retrieving the URL of an emote::
* Usage: `showEmote <emote>`
* Description: Posts the name of the emote accompanied with the URL where the image of the emote is stored.

Displaying the avatar or a member::
* Usage: `showAvatar [member]`
* Description: Displays the avatar of the given member accompanied with a URL to access it directly. If no member is provided, the member executing will be used.

Displaying information about members::
* Usage: `userInfo [member]`
* Description: Displays information about a member including: username, ID, activity, nickname (if any), date joined the server and date registered on discord.

Displaying information about the server::
* Usage: `serverInfo`
* Description: Displays information about the server including: ID, server name, owner, member count, creation date, role count, server features and custom emotes of the server.

=== Link embeds

==== Emotes
* `removeEmbed` to remove the embed of a link

This feature enables the automatic embedding of messages containing a message link.
If a message contains a link to a discord message this will create an embed containing the the message content. This supports image attachments, but not videos or files.
A reaction is placed on the embedded message which can be used to delete this embed. Only the original author and the person creating the embed can delete the embed this way.

Feature key: `link_embeds`

=== Repost detection and tracking

This feature can be used to detect whether an image has been posted before on the server. Images are compared by the hash stored in the database, which makes it very strict.
In order to calculate the hash, the image needs to be downloaded. It is possible to show a leaderboard of the most reposting users. Both of these features can be changed via feature modes.
If a reaction has been detected a reaction will be added to the post. If a message contains multiple or the detected repost is not the first image in the message a reaction containing digit indicating the position of the repost will be added.
For example if the repost is the second image in a message, a reaction representing the digit two will be added.

While it can be configured that the feature is only active in certain channels, the detection whether an image is a repost checks all previously posted images from the server (given they have been posted in a channel where the repost check is active).

Feature key: `repostDetection`

==== Feature modes
`download`:: If this is enabled, the images in the configured channels will be downloaded and the hash is calculated basd on the file content. The images are deleted immediately afterwards. If this is disabled, the proxy URL of the image will be used to calculate the hash. Enabled by default.
`leaderboard`:: If this is enabled, the command `repostLeaderboard` will be available. This command shows the leaderboard of the user with the most reposts. Disabled by default.

==== Emotes
* `repostMarker` to indicate that a post has been identified as a repost

==== Commands
Remove stored image posts and reposts of whole server or specific member::
* Usage: `purgeImagePosts [member]`
* Description: If `member` is provided, this will delete all stored image hashes (and their reposts) from the database. If `member` is not provided, this will delete all stored image hashes (and their reposts) from the whole server.

Remove reposts of whole server or specific member::
* Usage: `purgeReposts [member]`
* Description: If `member` is provided, this will delete all reposts of the given member. If `member` is not provided, this will delete all reposts in the whole server.

Show the leaderboard of reposts::
* Usage: `repostLeaderboard [page]`
* Description: Shows the rank and the amount of reposts for a provided `page`, if `page` is not provided, it will show five users with the highest a mount of reposts. `page` is 1-indexed. It will also show the amount and rank of the user executing.
* Mode Restriction: This command is only available when the feature mode `leaderboard` is enabled.

Enable repost check for a channel group::
* Usage: `enableRepostCheck <groupName>`
* Description: Enables the repost checking for all channels in the channel group identified by `groupName`. This channel group needs to be of type `repostCheck`.

Disable repost check for a channel group::
* Usage: `disableRepostCheck <groupName>`
* Description: Disables the repost checking for all channels in the channel group identified by `groupName`. This channel group needs to be of type `repostCheck`.

Show the channels for which repost check has been enabled::
* Usage: `showRepostCheckChannels`
* Description: Shows the channel groups with their respective channels for which the repost check has been enabled. These can only be channel groups of type `repostCheck`. It can still be enabled if there are now channels in the channel group.