# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Execute build and Sonar

on:
  push:
    branches:
      - master
      - feature/**
      - hotfix/**
      - bugfix/**
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B install --file abstracto-application/pom.xml
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v1
    - name: Run sonarqube
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sonar-scanner
       -Dsonar.login=${{ secrets.SONAR_TOKEN }}
       -Dsonar.organization=sheldan
       -Dsonar.host.url=https://sonarcloud.io/
       -Dsonar.projectKey=abstracto-abstracto
       -Dsonar.java.binaries=**/target/classes
       -Dsonar.coverage.jacoco.xmlReportPaths=abstracto-application/coverage/target/site/jacoco-aggregate/jacoco.xml
       -Dsonar.coverage.exclusions=**/*Test.java
